// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/sources/vector_store.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8908478035516613134),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(5, 5265777330473282763),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8283539601921984041),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6132400790006226054),
        name: 'docId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 3394855078667721877),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6812826053694757501),
        name: 'ordinal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5314880424897439057),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5265777330473282763),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 4501562972594563632),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5823116824665715704),
    name: 'IngestedDocument',
    lastPropertyId: const obx_int.IdUid(7, 6417658989410312728),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6099967303366965383),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3476911894186666596),
        name: 'docId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 879101891715931992),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5692092058519536944),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1326660741503113298),
        name: 'sourcePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8912786406901752399),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4718477778077471909),
        name: 'embedModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6417658989410312728),
        name: 'ingestedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// Use [obx.Store.new] directly to use all its options. See its
/// documentation for an explanation of all parameters.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5823116824665715704),
    lastIndexId: const obx_int.IdUid(3, 879101891715931992),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final docIdOffset = fbb.writeString(object.docId);
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, docIdOffset);
        fbb.addInt64(2, object.ordinal);
        fbb.addOffset(3, textOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final docIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 6, '');
        final ordinalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 10, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final object = DocumentChunk(
          id: idParam,
          docId: docIdParam,
          ordinal: ordinalParam,
          text: textParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    IngestedDocument: obx_int.EntityDefinition<IngestedDocument>(
      model: _entities[1],
      toOneRelations: (IngestedDocument object) => [],
      toManyRelations: (IngestedDocument object) => {},
      getId: (IngestedDocument object) => object.id,
      setId: (IngestedDocument object, int id) {
        object.id = id;
      },
      objectToFB: (IngestedDocument object, fb.Builder fbb) {
        final docIdOffset = fbb.writeString(object.docId);
        final titleOffset = fbb.writeString(object.title);
        final sourcePathOffset = fbb.writeString(object.sourcePath);
        final embedModelIdOffset = fbb.writeString(object.embedModelId);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, docIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, sourcePathOffset);
        fbb.addInt64(4, object.chunkCount);
        fbb.addOffset(5, embedModelIdOffset);
        fbb.addInt64(6, object.ingestedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final docIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 8, '');
        final sourcePathParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 10, '');
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final embedModelIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 14, '');
        final ingestedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = IngestedDocument(
          id: idParam,
          docId: docIdParam,
          title: titleParam,
          sourcePath: sourcePathParam,
          chunkCount: chunkCountParam,
          embedModelId: embedModelIdParam,
          ingestedAt: ingestedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.docId].
  static final docId = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.ordinal].
  static final ordinal = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.text].
  static final text = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[3],
  );

  /// See [DocumentChunk.embedding].
  static final embedding = obx.QueryHnswProperty<DocumentChunk>(
    _entities[0].properties[4],
  );
}

/// [IngestedDocument] entity fields to define ObjectBox queries.
class IngestedDocument_ {
  /// See [IngestedDocument.id].
  static final id = obx.QueryIntegerProperty<IngestedDocument>(
    _entities[1].properties[0],
  );

  /// See [IngestedDocument.docId].
  static final docId = obx.QueryStringProperty<IngestedDocument>(
    _entities[1].properties[1],
  );

  /// See [IngestedDocument.title].
  static final title = obx.QueryStringProperty<IngestedDocument>(
    _entities[1].properties[2],
  );

  /// See [IngestedDocument.sourcePath].
  static final sourcePath = obx.QueryStringProperty<IngestedDocument>(
    _entities[1].properties[3],
  );

  /// See [IngestedDocument.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<IngestedDocument>(
    _entities[1].properties[4],
  );

  /// See [IngestedDocument.embedModelId].
  static final embedModelId = obx.QueryStringProperty<IngestedDocument>(
    _entities[1].properties[5],
  );

  /// See [IngestedDocument.ingestedAt].
  static final ingestedAt = obx.QueryDateProperty<IngestedDocument>(
    _entities[1].properties[6],
  );
}
