/// How a template's text turns into the prompt a step is actually asked.
///
/// A template refers to values two ways, and both come through the one
/// resolver here:
///
/// * **`reads`** — a structured list the pipeline builder's READS dropdown
///   produces. Each reference is rendered into the prompt as a labelled block,
///   which is how step two sees what step one found.
/// * **`{{input.query}}` / `{{step.search}}`** — placeholders inside the
///   prompt itself, for a template written by hand that wants a value in the
///   middle of a sentence rather than appended at the end.
///
/// A reference is `input.<name>` or `step.<id>`. There is no expression
/// language and there will not be one: a template is authored by a person or
/// generated by a form, and anything cleverer than substitution becomes a
/// thing to debug on a phone with no console.
library;

/// The values a step can read, built up as the run proceeds.
class AgentScope {
  AgentScope({Map<String, String>? inputs})
    : _inputs = <String, String>{...?inputs};

  final Map<String, String> _inputs;
  final Map<String, String> _steps = <String, String>{};

  /// What the user typed, by input name.
  Map<String, String> get inputs => Map<String, String>.unmodifiable(_inputs);

  /// What each finished step produced, by step id.
  Map<String, String> get steps => Map<String, String>.unmodifiable(_steps);

  /// Records [output] as the result of step [id].
  void record(String id, String output) => _steps[id] = output;

  /// The value [reference] points at, or null when it points at nothing.
  ///
  /// Null rather than an empty string, so a caller can tell "the template
  /// names something that does not exist" — a mistake — from "the step ran and
  /// produced nothing", which is an ordinary outcome.
  String? resolve(String reference) {
    final (namespace, key) = _split(reference);
    return switch (namespace) {
      'input' => _inputs[key],
      'step' => _steps[key],
      _ => null,
    };
  }

  /// What a reference is called on screen: `Query`, not `input.query`.
  static String labelFor(String reference) {
    final (namespace, key) = _split(reference);
    final words = key
        .split(RegExp('[_.-]'))
        .where((word) => word.isNotEmpty)
        .map((word) => '${word[0].toUpperCase()}${word.substring(1)}')
        .join(' ');
    return switch (namespace) {
      'step' => 'Result of $words',
      _ => words,
    };
  }

  static (String, String) _split(String reference) {
    final dot = reference.indexOf('.');
    if (dot < 0) return ('', reference);
    return (reference.substring(0, dot), reference.substring(dot + 1));
  }
}

/// Replaces every `{{reference}}` in [template] with its value.
///
/// A reference that resolves to nothing becomes an empty string rather than
/// being left as `{{...}}` on screen — the model would read the braces as
/// content and sometimes copy them into its answer. The validator is what
/// catches a reference that can never resolve; by the time a run starts, an
/// empty one means the step genuinely produced nothing.
String renderTemplate(String template, AgentScope scope) =>
    template.replaceAllMapped(
      RegExp(r'\{\{\s*([A-Za-z0-9_.]+)\s*\}\}'),
      (match) => scope.resolve(match.group(1) ?? '') ?? '',
    );

/// Every `{{reference}}` named in [template], in the order they appear.
List<String> referencesIn(String template) => <String>[
  for (final match in RegExp(
    r'\{\{\s*([A-Za-z0-9_.]+)\s*\}\}',
  ).allMatches(template))
    match.group(1) ?? '',
];

/// The full prompt for one step: the instruction, then a labelled block per
/// reference in [reads].
///
/// The blocks go after the instruction, not before. A small model follows the
/// last thing it read, and putting four thousand characters of scraped page
/// between the instruction and the end of the prompt is how an agent ends up
/// summarising the page instead of doing what it was asked.
String buildStepPrompt({
  required String instruction,
  required List<String> reads,
  required AgentScope scope,
}) {
  final blocks = <String>[];
  for (final reference in reads) {
    final value = scope.resolve(reference)?.trim() ?? '';
    if (value.isEmpty) continue;
    blocks.add('${AgentScope.labelFor(reference)}:\n$value');
  }

  final rendered = renderTemplate(instruction, scope).trim();
  if (blocks.isEmpty) return rendered;
  return '${blocks.join('\n\n')}\n\n$rendered';
}
